import { StandardTableView, Button, HorizontalBox} from "std-widgets.slint";

export component Example inherits Window {
    width: 2000px;
    height: 600px;
    title: "Table Viewer";
    icon: @image-url("./table.png");
    callback button_pressed<=>btn_open.clicked;
    in-out property <[TableColumn]> headers<=>tb1.columns;
    in-out property <[[StandardListViewItem]]> datas<=>tb1.rows;

    VerticalLayout {
      HorizontalBox {
        btn_open:=Button {
          text: "Open";
          width: 100px;
        }
        Button {
          text: "Close";
          width: 100px;
          clicked => {
            tb1.columns=[];
            tb1.rows=[];
          }
        }
      }
      tb1:=StandardTableView {
        width: root.width;
        height: root.height;
        columns: [
            { title: "Header 1" },
            { title: "Header 2" },
            { title: "Header 3" },
            { title: "Header 4" },
        ];
        rows: [
          [{text:"value1"},{text:"value1"},{text:"value1"},{text:"value1"},],
          [{text:"value1"},{text:"value1"},{text:"value1"},{text:"value1"},],
          [{text:"value1"},{text:"value1"},{text:"value1"},{text:"value1"},],
          [{text:"value1"},{text:"value1"},{text:"value1"},{text:"value1"},],
        ];
    }
    }
}
